language: scala
scala:
  - 2.11.8

jdk:
  - oraclejdk8

# this is the actual script
script: sbt run

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "AOlEhsZVZuMeDh4TRQ/p9oV5H70lxG/7QJXn/QnpmWvg9l7M6ZGnOfDutLZ84CApvEyHHdrjlXbYLPuJDPqaB3BepjoRztdyfE2ZMGfdbgHaAgrSneHth66xYdqPYJYFnrYd+oOf4uT5gHPvZIFbf1uh+9hZrIIVZCptMGlEZvPnPTjXLNw/blTp97mqarG+0WA2mqnWXA/0FaZrmRlb4zgd535fGR1x3XqT99/TnRN7/Cu+gFSQKv6b9CHdz8NNWODX+SVthNFoeah7N5cOABLlTsZXaI7FWVBSkvLGBe/b2aPUOXmS03kqmqZCo77Xc3iexvlXbxqxgDsQs0tUQf+p4D+9rQiRxTfETGiGijzAtQecuH9ql4JM+ys94TlHjXSA3OUvAHGKNTbMQtMgYVYI3FQk6hBiDM3Uib7MeWz8yf4M4bKdvu3uMEjMqYcPhe9Qp521OPpYwzxo4WJaz/wPZPtyheFl+2yFotSbmq6HvgTQ9TLttaE1efnDBJoE6nc8orct7zDNy5VnuI20/A0V0kxQBHn1Tc7HhZ5iKCnyeOEIT+Kdedrc2Czof4/8KEdvFLsmn6yOAgkEHNetVFKDSlyVAX5FQU3E4hmWqlxOJdaJEv5RyyFvlEDdOUYLkbFGSOHvSIGLuQyMT4wac5bOX+uvZCw5UWXhV1HWB5s="
    file_glob: true
    file: target/bukkit-*.tgz
    overwrite: true
    on:
      repo: jastice/dash-bukkit
      tags: true

# we don't need sudo, this allows container-based builds ...
sudo: false

# ... which allows caching of .m2 and makes builds faster

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.m2/
